version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "{{ cookiecutter.default_python }}"
  jobs:
    post_create_environment:
      - pip install uv
    install:
      - ./install.sh --all-extras --groups=docs
    pre_build:
      - sphinx-apidoc -f -o docs {{ cookiecutter.project.name }}
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
